### ISSUE TITLE
[PROPOSAL] Is this the semantic-reranker or relevance_workbench repo?

### ISSUE THREAD

**Issue by macohen** [opensearch-project/search-processor#17]
### What are you proposing?
I think we’re about to hit a conflict here and could use help from the more experienced team members. With the semantic-reranker plugin here https://github.com/kevinawskendra/search-relevance and the relevancy_workbench here https://github.com/ps48/search-relevance/tree/relevancy_workbench, we probably want to set a new origin for one of them and create a new repo according to this: https://github.com/opensearch-project/opensearch-plugin-template-java. Are my assumptions sound? 

If so, then I think it makes the most sense to put relevancy_workbench here and create a new repo for the semantic-reranker according to [GitHub - opensearch-project/opensearch-plugin-template-java: Template repo for creating OpenSearch plugins](https://github.com/opensearch-project/opensearch-plugin-template-java)/

**Comment by anirudha** [comment]
Historically repos opensearch-project could be structured by product boundaries or by plugin boundaries. Due to recent limitations in in CI / efficiencies in CI. we decided to align repos by plugin boundaries.

The Search Relevancy product would have 1. OpenSearch plugin (Engine) and 2. Dashboards plugin (UI).
With the new guidance, we need to create another repo for the one plugin.

I recommend the following repos.
1. search-relevance ( opensearch)
2. dashboards-search-relevance.

There is no specific plugin repo for a re-ranker, all re-ranker impl. could be shipped as a meta-plugin in the search-relevance repo while adhering to the request/response chaining mechanisms

**Comment by macohen** [comment]
Is a "meta-plugin" something concrete and different than an OpenSearch plug-in or is it just a plugin that allows different providers to integrate their own code in packages in the same repo?

**Comment by macohen** [comment]
request made to create a dashboards-search-relevance repo. closing this issue.
